filepath_samples: idc/data/pbmc_x.npz
num_clusters: 2

batch_size: 256
seeds: 1
epochs: &epochs 200

ae_non_gated_epochs: 5 #50 we reduce the number of epochs for training inside a notebook
ae_pretrain_epochs: 10 #100 we reduce the number of epochs for training inside a notebook
start_global_gates_training_on_epoch: 150

mask_percentage: 0.9
latent_noise_std: 0.01

trainer:
  devices: 1
  accelerator: gpu
  max_epochs: *epochs
  deterministic: true
  logger: true
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  enable_checkpointing: false
  num_sanity_val_steps: 0


# GTCR loss
gtcr_loss: true
gtcr_projection_dim: 1024 # for large number of features use it
gtcr_eps: 1


# Compression loss
eps: 0.1

# Gating Net
use_gating: true
gates_hidden_dim: 1024

# EncoderDecoder
encdec:
  - 512
  - 512
  - 2048
  - &bn_layer 128
  - 2048
  - 512
  - 512

clustering_head:
  - *bn_layer
  - 2048

tau: 100

aux_classifier:
  - 2048

local_gates_lambda: 100
global_gates_lambda: 10
gtcr_lambda: 0.01

lr:
  pretrain: 1e-3
  clustering: 1e-3
  aux_classifier: 1e-1

sched:
  pretrain_min_lr: 1e-4
  clustering_min_lr: 1e-4

save_seed_checkpoints: false
